// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlwajdmidvcxesriymoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd2FqZG1pZHZjeGVzcml5bW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTM4MTAsImV4cCI6MjA3MzM2OTgxMH0.BV-A-uqQ1_zIdGVf8sMIG27pWwIrkdJYYM9J1vr2mDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});